import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_ringtone_player/flutter_ringtone_player.dart';

import 'core/constants/app_constants.dart';
import 'core/router/app_router.dart';
import 'core/router/routes.dart';
import 'core/theme/app_theme.dart';
import 'firebase_options.dart';
import 'providers/call_providers.dart';
import 'providers/user_providers.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Must complete before any FirebaseAuth / FirebaseDatabase instance is
  // touched. Providers create those lazily, so awaiting here guarantees the
  // first provider read happens against an initialised app.
  //
  // firebase_options.dart is generated by `flutterfire configure` and is
  // gitignored; see the README setup section.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ProviderScope(child: ConnectCallApp()));
}

class ConnectCallApp extends ConsumerWidget {
  const ConnectCallApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    // Session-wide background work, started at the root so it runs for as
    // long as someone is signed in, regardless of which screen is showing.
    // Both react to the signed-in uid on their own, starting on login and
    // stopping on logout.
    //  - presence: arms the server-side onDisconnect that marks the user
    //    offline even if the app is killed or loses signal
    //  - incoming calls: must be listening wherever the user is in the app
    ref.watch(presenceControllerProvider);
    ref.watch(incomingCallListenerProvider);

    // The call screen follows the call. It opens when a call starts or
    // arrives and closes when the controller clears a finished one. Screens
    // never push or pop it themselves, so the UI cannot disagree with the
    // controller about whether a call is happening.
    ref.listen<ActiveCall?>(callControllerProvider, (previous, next) {
      // Read the *top* of the route stack, not currentConfiguration.uri: per
      // go_router, that uri "only reflects RouteMatches that are not
      // ImperativeRouteMatch", i.e. it ignores pushed routes. Checking it
      // made this listener believe the pushed call screen was never showing,
      // so it never popped and a finished call left a blank screen.
      final matches = router.routerDelegate.currentConfiguration.matches;
      final onCallScreen =
          matches.isNotEmpty && matches.last.matchedLocation == Routes.call;

      if (previous == null && next != null && !onCallScreen) {
        router.push(Routes.call);
      } else if (previous != null && next == null && onCallScreen) {
        router.pop();
      }
    });

    // Ring while an incoming call is waiting on this device, and stop the
    // moment that stops being true: answered, declined, cancelled by the
    // caller, or missed. Driven from the controller state in one place rather
    // than by the incoming screen, so no exit path can leave the phone ringing
    // after the call has gone.
    ref.listen<bool>(
      callControllerProvider.select((call) => call?.isIncomingRinging ?? false),
      (previous, ringing) {
        final player = FlutterRingtonePlayer();
        if (ringing) {
          player.playRingtone(looping: true);
        } else {
          player.stop();
        }
      },
    );

    return MaterialApp.router(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      // Follows the device setting. Bonus 3 (dark mode) is satisfied by
      // building both themes from the same tokens rather than bolting on
      // a second palette later.
      themeMode: ThemeMode.system,
      routerConfig: router,
    );
  }
}
